// <auto-generated />
using System;
using Fiap.Banco.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Banco.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Banco.API.Models.Agencia", b =>
                {
                    b.Property<int>("idAgencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAgencia"));

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("nmEndereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.HasKey("idAgencia");

                    b.ToTable("AgenciaBanco", (string)null);
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Bancos", b =>
                {
                    b.Property<int>("idBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idBanco"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("nomeBanco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("idBanco");

                    b.ToTable("Bancos", (string)null);
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCliente"));

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<int>("idAgencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nmCliente")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.HasKey("idCliente");

                    b.HasIndex("idAgencia");

                    b.ToTable("ClientesBanco", (string)null);

                    b.HasDiscriminator<string>("TipoCliente").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Contratacao", b =>
                {
                    b.Property<int>("idContratacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idContratacao"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MensagemProcessamento")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<int>("Tentativas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("idAgencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("idCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("idProduto")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("idContratacao");

                    b.HasIndex("idAgencia");

                    b.HasIndex("idCliente");

                    b.HasIndex("idProduto");

                    b.ToTable("Contratacoes", (string)null);
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Produto", b =>
                {
                    b.Property<int>("idProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProduto"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.Property<string>("nmProduto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.HasKey("idProduto");

                    b.ToTable("Produtos", (string)null);

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Cliente");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasFilter("\"CPF\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Cliente");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasFilter("\"CNPJ\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Emprestimo", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<int>("Parcelas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasDiscriminator().HasValue("EMPRESTIMO");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<decimal>("TaxaPercentual")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<decimal>("VolumeMensalEstimado")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasDiscriminator().HasValue("MAQUINA_CARTAO");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.ReceberSalario", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<string>("EmpresaConveniada")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<decimal>("SalarioMensal")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasDiscriminator().HasValue("RECEBER_SALARIO");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("idAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Contratacao", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Agencia", "Agencia")
                        .WithMany("Contratacoes")
                        .HasForeignKey("idAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.Banco.API.Models.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.Banco.API.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("idProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Agencia", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
